---
title: "Data Cleaning/Wrangling"
author: "Clara Seo"
date: "9/29/2020"
output: pdf_document
---

```{r setup, include=FALSE}
library(readtext)
library(tidytext)
library(tidyverse)
library(dplyr)
library(tidyr)
library(kableExtra)
knitr::opts_chunk$set(echo = TRUE)
```

```{r data read-in}
# Read in all files from a folder called "chapter_files"
text <- as.data.frame(readtext("chapter_files/*.txt"))
```

```{r}
# mega-function that 1) renames chapters 
#                    2) removes hyphens, miscellaneous punctuation
clean_data <- function(df){
  
  n_chapters <- nrow(df)

  # STEP 1: rename chapters in doc_id from chapter##.txt to chapter##
  for(i in 1:n_chapters){
    df[i,1] <- paste("chapter", i-1, sep="")
  }
  
  # function to remove hyphens and merge hyphenated words
  removeHyphen_concat <- function(chapter_num) {
    chapter <- df[chapter_num+1,2]
    
    # strsplit returns a list: we only want the first element
    chapter <- stringr::str_split(chapter, "\n")[[1]]
    
    # remove whitespaces on the right side (at end of line)
    chapter <- str_trim(chapter, side = "both")
  
    # determine which lines end with hyphen
    is_end_hyphen <- str_detect(chapter, regex("\\-$"))
  
    for (r in 1:length(is_end_hyphen)) {
      if (is_end_hyphen[r] == TRUE) {
        # extract second-half of hyphenated word, delete from carry-over line
        second_half <- str_extract(chapter[r + 1], regex("^\\w+"))
        chapter[r + 1] <- gsub(
          str_extract(chapter[r + 1], regex("^\\w+")), "",
          chapter[r + 1]
        )
        chapter[r + 1] <- str_trim(chapter[r + 1], side = "left")
  
        # delete the end-hyphen, concatenate first- and second-half of hyphenated word
        chapter[r] <- gsub("\\-$", "", chapter[r])
        chapter[r] <- paste(chapter[r], second_half, sep = "")
      }
    }
    
    # determine which lines start with punctuation
    is_start_punctuation <- str_detect(chapter, regex("^[[:punct:]]"))
    
    for (q in 1:length(is_start_punctuation)) {
      if (is_start_punctuation[q] == TRUE && !is.na(is_start_punctuation[q])) {
        
        # extract trailing punctuation, delete from carry-over line, trim spaces out
        punc_to_bring_over <- str_extract(chapter[q], regex("^[[:punct:]]"))
        chapter[q] <- str_remove(chapter[q],"^[[:punct:]]")
        chapter[q] <- str_trim(chapter[q], side = "left")
        
        # concatenate sentence with trailing punctuation
        chapter[q - 1] <- paste(chapter[q-1], punc_to_bring_over, sep="")
      }
    }
    
    chapter_collapse <- paste(chapter,collapse=" \n ") 
    return(chapter_collapse)
  }
  
  # STEP 2: use removeHyphen_concat() to remove hyphens and misc. punctuation
  for(i in 1:n_chapters){
    chapter_num <- i-1
    df[i,2] <- removeHyphen_concat(chapter_num)
  }
  
  return(df)
}
texts<- clean_data(text)

```

```{r}
 n_chapters <- nrow(texts)
text <- c("")
book<-data.frame(text)
```


```{r}
## This gets all the chapters into their own separate df's

for (i in 1:n_chapters) {
  # single string of text that contains the entire chapter
  temp_chapter <- texts[i, 2]
  string_chapter <- stringr::str_split(temp_chapter, "\n")[[1]]
  num_lines <- length(string_chapter)
  chapter_df <- tibble(line = 1:num_lines, text = string_chapter) %>% select(text)
  book <- rbind(book, chapter_df)
  # rename string with appropriate chapter number
  assign(paste("chapter", i - 1, "_df", sep = ""), chapter_df)
}

```


